USE FRIENDSLOCATION
GO


IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME = 'FRIEND' AND TYPE = 'U')
   BEGIN
 
      CREATE TABLE DBO.FRIEND (ID        INT IDENTITY NOT NULL,
                               NOME      VARCHAR(100) NOT NULL,
							   GENERO    CHAR(1) NOT NULL,
                               LATITUDE  FLOAT NOT NULL,
                               LONGITUDE FLOAT NOT NULL)

      ALTER TABLE DBO.FRIEND ADD CONSTRAINT PK_FRIEND 
	                         PRIMARY KEY (ID)
   END

GO



-- CARGA DOS AMIGOS
BEGIN TRAN

DELETE FROM FRIEND


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Bruce Wayne', 'M', 15.596956, 18.685969)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Clark Kente', 'M', -9.4236953, 12.415836)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Dick Grayson', 'M', -5.857410, -9.495368)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Peter Parker', 'M', 75.653298, -89.639584)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Sue Richards', 'F', 65.964258, -10.236525)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Diana de Themyscira',  'F', -45.964258, -29.236525)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Bruce Barner', 'M', 32.420102, -3.470360)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Natasha Romanova', 'F', -2.420102, 83.470360)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Alfred Peniwhise', 'M', 16.365263, 19.562485)


INSERT INTO FRIEND (NOME, GENERO, LATITUDE, LONGITUDE)
VALUES             ('Wade Wilson', 'M', -55.694258, 89.653297)


COMMIT TRAN

GO

